# Jekyll configuration for FerretWatch Enhanced Documentation
title: FerretWatch Enhanced
description: Privacy-preserving browser extension for suspicious page detection
baseurl: ""
url: "https://cybercyberlabs.github.io/ferretwatch"

# Jekyll settings
markdown: kramdown
highlighter: rouge
theme: just-the-docs

# Just the Docs theme settings
color_scheme: ferretwatch
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

heading_anchors: true
aux_links:
  "FerretWatch on GitHub":
    - "https://github.com/cybercyberlabs/ferretwatch"

# Footer content
footer_content: "Copyright &copy; 2025 CyberCyberLabs. Distributed by an <a href=\"https://github.com/cybercyberlabs/ferretwatch/tree/docs/product-specifications/LICENSE\">MIT license.</a>"

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Just the Docs navigation - uses nav_order in front matter
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/cybercyberlabs/ferretwatch

# Defaults for Just the Docs
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Site settings
author:
  name: FerretWatch Team
  email: team@ferretwatch.com

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore
  - .github/
  - _sass/
  - _layouts/
  - _includes/

# Include files
include:
  - _pages